#!/bin/sh

### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##
#
#   Copyright J. Craig Venter Institute 2012
#   See docs.PGP/COPYING file distributed along with the proteogenomics 
#   package for the copyright and license terms.
#
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##

set -ex

#you need to source PGP environment file first
[ -n "$PGP_VENDOR_HOME" ] || exit 1

NAME=productionPepNovo

PREFIX=$PGP_VENDOR_HOME/$NAME

#using our patched sources (include <cstring>)
BUILD=$NAME
SOURCE=$BUILD.tar.gz
rm -rf $BUILD
tar -zxf $SOURCE

pushd $BUILD
pushd src
make
mkdir $PREFIX
cp -a PepNovo_bin $PREFIX
popd
cp -a copyright.txt  Models  MS-Filter.readme.txt readme.txt $PREFIX
