#!/bin/bash
set -ex

config_dir=$(cd $(dirname $0) && pwd)

. $config_dir/pgp_makeflow_env_master.sh

mkdir -p $PGP_VENDOR_HOME

export PGP_VENDOR_BUILD=$PGP_ROOT/build/vendor

cd $PGP_VENDOR_BUILD

$config_dir/install_makeflow

#unpack seqan and build the Python extension
PGP_SEQAN_VER=1.3.1
unzip seqan-$PGP_SEQAN_VER.zip
export PGP_SEQAN_HOME=$PGP_VENDOR_BUILD/seqan-$PGP_SEQAN_VER
#@todo: make it generic to build at JCVI too, and use setup.py
(cd $PGP_HOME/seqan && ./build_ranger.sh)

$config_dir/install_pepnovo

#no build for MSGF, source is not available, just unpack the jar
(cd $PGP_VENDOR_HOME && tar -zxf $PGP_VENDOR_BUILD/MSGF.tar.gz)

echo "BUILD COMPLETE!!!"
echo "To generate the Makeflow input for the pipeline:"
echo "source $config_dir/pgp_makeflow_env_master.sh"
echo "python $PGP_HOME/PGPMakeflow.py --help"
echo "and follow the help printout."
echo "Once the Makeflow file is generated,"
echo "you can copy and modify a sample qsub script"
echo "from $config_dir/ranger_run"

