#!/bin/sh

### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##
#
#   Copyright J. Craig Venter Institute 2012
#   See docs.PGP/COPYING file distributed along with the proteogenomics 
#   package for the copyright and license terms.
#
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##

set -ex

#you need to source PGP environment file first
[ -n "$PGP_VENDOR_HOME" ] || exit 1

MPI_PATH=$MPICH_HOME
PREFIX=$PGP_VENDOR_HOME

NAME=cctools
VER=3.4.3
#using our patched sources
BUILD=$NAME-$VER-src.at
SOURCE=$BUILD.tar.gz
rm -rf $BUILD
tar -zxf $SOURCE

pushd $BUILD
#needs GLOBUS 4 on Ranger, no way seen to disable GLOBUS altogether once found
./configure --with-mpi-path $MPI_PATH --with-globus-path $GLOBUS_PATH --prefix $PREFIX
make
make install
